"""
Generates the flamethrower weapon's art: the pickup icon dropped by
Crawlers and the flame-particle "bullet" fired while it's active. Same
pipeline as gen_hud_sprites.py/gen_shop_sprites.py: draw once with Pillow,
emit source/weapon_sprites_data.h (RGB15+alpha) and a labeled preview PNG.

Run with: python tools/gen_weapon_sprites.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(OUT_DIR)

TRANSPARENT = (0, 0, 0, 0)

FLAME_DARK = (150, 20, 10, 255)
FLAME_MID  = (230, 90, 20, 255)
FLAME_HOT  = (255, 175, 40, 255)
FLAME_CORE = (255, 240, 140, 255)


def new_sprite(w, h):
    return Image.new("RGBA", (w, h), TRANSPARENT)


def _flame_blob(d, cx, cy, r):
    # a teardrop-ish flame silhouette built from a couple of overlapping shapes
    d.ellipse([cx - r, cy - r * 0.2, cx + r, cy + r * 1.6], fill=FLAME_DARK)
    d.polygon([(cx, cy - r * 1.3), (cx - r * 0.8, cy + r * 0.6), (cx + r * 0.8, cy + r * 0.6)], fill=FLAME_DARK)


def draw_powerup_flame(size=8):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx, cy = size / 2, size / 2 + 1
    _flame_blob(d, cx, cy, 3.6)
    d.ellipse([cx - 2.2, cy - 1.6, cx + 2.2, cy + 2.6], fill=FLAME_MID)
    d.ellipse([cx - 1.2, cy - 0.2, cx + 1.2, cy + 2.2], fill=FLAME_HOT)
    d.point([(cx, cy + 1)], fill=FLAME_CORE)
    return img


def draw_flame_bullet(size=8):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx, cy = size / 2, size / 2
    _flame_blob(d, cx, cy, 3.2)
    d.ellipse([cx - 2, cy - 1.4, cx + 2, cy + 2.4], fill=FLAME_MID)
    d.ellipse([cx - 1, cy - 0.2, cx + 1, cy + 1.8], fill=FLAME_HOT)
    d.point([(cx, cy + 0.5)], fill=FLAME_CORE)
    return img


SPRITES = [
    ("POWERUP_FLAME", draw_powerup_flame(8), 8),
    ("FLAME_BULLET", draw_flame_bullet(8), 8),
]


def to_rgb15(img):
    w, h = img.size
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            r5 = (r * 31 + 127) // 255
            g5 = (g * 31 + 127) // 255
            b5 = (b * 31 + 127) // 255
            alpha_bit = 0x8000 if a > 127 else 0
            out.append(alpha_bit | (b5 << 10) | (g5 << 5) | r5)
    return out


def write_header():
    path = os.path.join(PROJECT, "source", "weapon_sprites_data.h")
    with open(path, "w") as f:
        f.write("// Generated by tools/gen_weapon_sprites.py - do not edit by hand.\n")
        f.write("#ifndef BUGSWARM_WEAPON_SPRITES_DATA_H\n#define BUGSWARM_WEAPON_SPRITES_DATA_H\n\n")
        f.write('#include "globals.h"\n\n')
        for name, img, _size in SPRITES:
            data = to_rgb15(img)
            f.write(f"static const u16 SPR_{name}[{len(data)}] = {{\n")
            for i in range(0, len(data), 12):
                row = ", ".join(f"0x{v:04X}" for v in data[i:i + 12])
                f.write(f"    {row},\n")
            f.write("};\n\n")
        f.write("#endif\n")
    print("wrote", path)


def write_preview():
    scale = 12
    pad = 2
    label_h = 12
    cell_px = 8 * scale
    cols = 2
    sheet_w = cols * (cell_px + pad * 2)
    sheet_h = cell_px + pad * 2 + label_h

    sheet = Image.new("RGBA", (sheet_w, sheet_h), (24, 24, 32, 255))
    d = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    for idx, (name, img, size) in enumerate(SPRITES):
        ox = idx * (cell_px + pad * 2) + pad
        oy = pad

        check = Image.new("RGBA", (cell_px, cell_px), (40, 40, 52, 255))
        cd = ImageDraw.Draw(check)
        step = scale * 2
        for yy in range(0, cell_px, step):
            for xx in range(0, cell_px, step):
                if ((xx // step) + (yy // step)) % 2 == 0:
                    cd.rectangle([xx, yy, xx + step - 1, yy + step - 1], fill=(52, 52, 66, 255))
        sheet.alpha_composite(check, (ox, oy))

        big = img.resize((size * scale, size * scale), Image.NEAREST)
        sheet.alpha_composite(big, (ox, oy))
        d.rectangle([ox, oy, ox + cell_px - 1, oy + cell_px - 1], outline=(90, 90, 110, 255))

        label = f"{name} {size}x{size}"
        tw = d.textlength(label, font=font) if font else len(label) * 6
        d.text((ox + (cell_px - tw) / 2, oy + cell_px + 1), label, fill=(230, 230, 240, 255), font=font)

    out_path = os.path.join(OUT_DIR, "weapon_sprites_preview.png")
    sheet.convert("RGB").save(out_path)
    print("wrote", out_path)


if __name__ == "__main__":
    write_header()
    write_preview()
