"""
Generates Bug Swarm's sub-screen HUD icon/gauge art (coin, heart, and the
analog heat-gauge dial + needle), the same way gen_sprites.py handles the
gameplay sprites: draw once with Pillow, emit an RGB15+alpha C header
(source/hud_sprites_data.h) plus a labeled preview PNG.

The gauge is a real semicircular dial (colored green/yellow/red zones) with
a separate needle sprite that source/hud.c rotates at runtime with the DS's
affine sprite hardware (oamRotateScale) - not a redraw, an actual rotation.
The needle art points LEFT at its neutral (unrotated) pose, pivoting from
the center of its own 16x16 canvas, which source/hud.c places exactly on
the dial's pivot dot.

Run with: python tools/gen_hud_sprites.py
"""

import os
import math
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(OUT_DIR)

TRANSPARENT = (0, 0, 0, 0)

GOLD_DARK = (150, 110, 10, 255)
GOLD      = (230, 185, 40, 255)
GOLD_HI   = (255, 235, 140, 255)

RED_DARK  = (110, 15, 20, 255)
RED       = (220, 45, 55, 255)
RED_HI    = (255, 150, 160, 255)

GREEN_ZONE  = (60, 170, 70, 255)
YELLOW_ZONE = (220, 185, 40, 255)
RED_ZONE    = (210, 60, 50, 255)
DIAL_DARK   = (30, 26, 24, 255)
DIAL_TICK   = (18, 16, 15, 255)
NEEDLE_COL  = (240, 240, 235, 255)
NEEDLE_TIP  = (255, 90, 70, 255)


def new_sprite(w, h):
    return Image.new("RGBA", (w, h), TRANSPARENT)


def draw_coin(size=8):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx = cy = size / 2 - 0.5
    r = size / 2 - 0.5
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=GOLD_DARK)
    d.ellipse([cx - r + 1, cy - r + 1, cx + r - 1, cy + r - 1], fill=GOLD)
    d.ellipse([cx - r + 3, cy - r + 3, cx, cy], fill=GOLD_HI)
    d.point([(cx, cy - 1), (cx, cy + 1)], fill=GOLD_DARK)
    return img


def draw_heart(size=8):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    # two lobes + a triangular base, hand-placed for a crisp tiny heart
    d.ellipse([0, 1, 4, 5], fill=RED_DARK)
    d.ellipse([3, 1, 7, 5], fill=RED_DARK)
    d.polygon([(0, 3), (7, 3), (3, 7)], fill=RED_DARK)
    d.ellipse([1, 1, 4, 4], fill=RED)
    d.ellipse([3, 1, 6, 4], fill=RED)
    d.polygon([(1, 3), (6, 3), (3, 6)], fill=RED)
    d.point([(2, 2)], fill=RED_HI)
    return img


def draw_gauge_dial(size=32):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx = cy = size / 2
    r_out = 15
    r_in = 9

    bands = [
        (180, 240, GREEN_ZONE),
        (240, 300, YELLOW_ZONE),
        (300, 360, RED_ZONE),
    ]
    for start, end, color in bands:
        d.pieslice([cx - r_out, cy - r_out, cx + r_out, cy + r_out], start, end, fill=color)
    d.pieslice([cx - r_in, cy - r_in, cx + r_in, cy + r_in], 180, 360, fill=TRANSPARENT)

    # tick marks at each zone boundary + the very ends
    for deg in (180, 240, 270, 300, 360):
        a = math.radians(deg)
        x0 = cx + math.cos(a) * (r_in - 1)
        y0 = cy + math.sin(a) * (r_in - 1)
        x1 = cx + math.cos(a) * (r_out + 1)
        y1 = cy + math.sin(a) * (r_out + 1)
        d.line([(x0, y0), (x1, y1)], fill=DIAL_TICK, width=1)

    # base plate + pivot the needle will sit on
    d.rectangle([cx - r_out, cy, cx + r_out, cy + 1], fill=DIAL_DARK)
    d.ellipse([cx - 3, cy - 3, cx + 3, cy + 3], fill=DIAL_DARK)
    d.ellipse([cx - 1.5, cy - 1.5, cx + 1.5, cy + 1.5], fill=(70, 65, 60, 255))
    return img


def draw_gauge_needle(size=16):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx = cy = size / 2 - 0.5
    length = 6.5
    # points LEFT at rest - source/hud.c rotates this sprite with oamRotateScale
    d.line([(cx, cy), (cx - length, cy)], fill=NEEDLE_COL, width=2)
    d.point([(cx - length, cy)], fill=NEEDLE_TIP)
    d.point([(cx - length + 1, cy - 1)], fill=NEEDLE_TIP)
    d.ellipse([cx - 1.5, cy - 1.5, cx + 1.5, cy + 1.5], fill=DIAL_DARK)
    return img


SPRITES = [
    ("COIN", draw_coin(8), 8),
    ("HEART", draw_heart(8), 8),
    ("GAUGE_DIAL", draw_gauge_dial(32), 32),
    ("GAUGE_NEEDLE", draw_gauge_needle(16), 16),
]


def to_rgb15(img):
    w, h = img.size
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            r5 = (r * 31 + 127) // 255
            g5 = (g * 31 + 127) // 255
            b5 = (b * 31 + 127) // 255
            alpha_bit = 0x8000 if a > 127 else 0
            out.append(alpha_bit | (b5 << 10) | (g5 << 5) | r5)
    return out


def write_header():
    path = os.path.join(PROJECT, "source", "hud_sprites_data.h")
    with open(path, "w") as f:
        f.write("// Generated by tools/gen_hud_sprites.py - do not edit by hand.\n")
        f.write("#ifndef BUGSWARM_HUD_SPRITES_DATA_H\n#define BUGSWARM_HUD_SPRITES_DATA_H\n\n")
        f.write('#include "globals.h"\n\n')
        for name, img, _size in SPRITES:
            data = to_rgb15(img)
            f.write(f"static const u16 SPR_{name}[{len(data)}] = {{\n")
            for i in range(0, len(data), 12):
                row = ", ".join(f"0x{v:04X}" for v in data[i:i + 12])
                f.write(f"    {row},\n")
            f.write("};\n\n")
        f.write("#endif\n")
    print("wrote", path)


def write_preview():
    scale = 10
    pad = 2
    label_h = 12
    cell = max(size for _, _, size in SPRITES)
    cols = 4
    rows = 1
    cell_px = cell * scale
    sheet_w = cols * (cell_px + pad * 2)
    sheet_h = rows * (cell_px + pad * 2 + label_h)

    sheet = Image.new("RGBA", (sheet_w, sheet_h), (24, 24, 32, 255))
    d = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    for idx, (name, img, size) in enumerate(SPRITES):
        ox = idx * (cell_px + pad * 2) + pad
        oy = pad

        check = Image.new("RGBA", (cell_px, cell_px), (40, 40, 52, 255))
        cd = ImageDraw.Draw(check)
        step = scale * 2
        for yy in range(0, cell_px, step):
            for xx in range(0, cell_px, step):
                if ((xx // step) + (yy // step)) % 2 == 0:
                    cd.rectangle([xx, yy, xx + step - 1, yy + step - 1], fill=(52, 52, 66, 255))
        sheet.alpha_composite(check, (ox, oy))

        big = img.resize((size * scale, size * scale), Image.NEAREST)
        inset = (cell_px - size * scale) // 2
        sheet.alpha_composite(big, (ox + inset, oy + inset))
        d.rectangle([ox, oy, ox + cell_px - 1, oy + cell_px - 1], outline=(90, 90, 110, 255))

        label = f"{name} {size}x{size}"
        tw = d.textlength(label, font=font) if font else len(label) * 6
        d.text((ox + (cell_px - tw) / 2, oy + cell_px + 1), label, fill=(230, 230, 240, 255), font=font)

    out_path = os.path.join(OUT_DIR, "hud_sprites_preview.png")
    sheet.convert("RGB").save(out_path)
    print("wrote", out_path)


if __name__ == "__main__":
    write_header()
    write_preview()
