"""
Generates Bug Swarm's shop-screen art: upgrade icons and tappable buttons.

Same pipeline as gen_sprites.py/gen_hud_sprites.py: draw once with Pillow,
emit source/shop_sprites_data.h (RGB15+alpha) and a labeled preview PNG.

Run with: python tools/gen_shop_sprites.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(OUT_DIR)

TRANSPARENT = (0, 0, 0, 0)

BOLT_DARK = (150, 110, 10, 255)
BOLT      = (250, 205, 40, 255)
BOLT_HI   = (255, 240, 150, 255)

ICE_DARK = (20, 90, 130, 255)
ICE      = (100, 200, 235, 255)
ICE_HI   = (210, 245, 255, 255)

HEART_DARK = (110, 15, 20, 255)
HEART      = (220, 45, 55, 255)
HEART_HI   = (255, 150, 160, 255)

BTN_BUY_DARK  = (20, 90, 35, 255)
BTN_BUY       = (45, 165, 70, 255)
BTN_BUY_HI    = (110, 220, 130, 255)

BTN_MAX_DARK = (55, 52, 50, 255)
BTN_MAX      = (95, 90, 86, 255)
BTN_MAX_HI   = (140, 135, 130, 255)

BTN_GO_DARK = (15, 75, 110, 255)
BTN_GO      = (35, 140, 200, 255)
BTN_GO_HI   = (140, 210, 250, 255)

WHITE = (250, 250, 250, 255)


def new_sprite(w, h):
    return Image.new("RGBA", (w, h), TRANSPARENT)


def draw_icon_rapid(size=16):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    bolt = [(9, 1), (4, 9), (7, 9), (6, 15), (12, 6), (9, 6)]
    outline = [(p[0] + dx, p[1] + dy) for p in bolt for dx, dy in [(0, 0)]]
    d.polygon([(x + 1, y) for x, y in bolt], fill=BOLT_DARK)
    d.polygon([(x - 1, y) for x, y in bolt], fill=BOLT_DARK)
    d.polygon(bolt, fill=BOLT)
    d.line([(9, 2), (6, 8)], fill=BOLT_HI, width=1)
    return img


def draw_icon_heat_resist(size=16):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    cx = cy = size / 2 - 0.5
    arms = 3
    length = 6.5
    import math
    for i in range(arms):
        a = math.pi * i / arms
        dx = math.cos(a) * length
        dy = math.sin(a) * length
        d.line([(cx - dx, cy - dy), (cx + dx, cy + dy)], fill=ICE_DARK, width=2)
        d.line([(cx - dx, cy - dy), (cx + dx, cy + dy)], fill=ICE, width=1)
        for t in (0.55, -0.55):
            bx = cx + dx * t
            by = cy + dy * t
            px = -dy * 0.3
            py = dx * 0.3
            d.line([(bx - px, by - py), (bx + px, by + py)], fill=ICE_DARK, width=1)
    d.ellipse([cx - 1.7, cy - 1.7, cx + 1.7, cy + 1.7], fill=ICE_HI)
    return img


def draw_icon_life(size=16):
    img = new_sprite(size, size)
    d = ImageDraw.Draw(img)
    d.ellipse([1, 2, 8, 9], fill=HEART_DARK)
    d.ellipse([7, 2, 14, 9], fill=HEART_DARK)
    d.polygon([(1, 6), (14, 6), (7.5, 15)], fill=HEART_DARK)
    d.ellipse([2, 3, 8, 9], fill=HEART)
    d.ellipse([7, 3, 13, 9], fill=HEART)
    d.polygon([(2, 6), (13, 6), (7.5, 13.5)], fill=HEART)
    d.ellipse([3, 4, 6, 7], fill=HEART_HI)
    return img


def _button(size, dark, mid, hi, w=32, h=16):
    img = new_sprite(w, h)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([0, 0, w - 1, h - 1], radius=4, fill=dark)
    d.rounded_rectangle([1, 1, w - 2, h - 3], radius=3, fill=mid)
    d.rounded_rectangle([2, 2, w - 3, h / 2], radius=2, fill=hi)
    return img, d


def draw_btn_buy(w=32, h=16):
    img, d = _button(None, BTN_BUY_DARK, BTN_BUY, BTN_BUY_HI, w, h)
    cx, cy = w / 2, h / 2
    d.line([(cx - 4, cy), (cx + 4, cy)], fill=WHITE, width=2)
    d.line([(cx, cy - 4), (cx, cy + 4)], fill=WHITE, width=2)
    return img


def draw_btn_max(w=32, h=16):
    img, d = _button(None, BTN_MAX_DARK, BTN_MAX, BTN_MAX_HI, w, h)
    cx, cy = w / 2, h / 2
    d.line([(cx - 4, cy), (cx - 1, cy + 3), (cx + 5, cy - 4)], fill=WHITE, width=2, joint="curve")
    return img


def draw_btn_continue(w=64, h=32):
    img, d = _button(None, BTN_GO_DARK, BTN_GO, BTN_GO_HI, w, h)
    cx, cy = w / 2 + 3, h / 2
    d.polygon([(cx - 8, cy - 9), (cx - 8, cy + 9), (cx + 9, cy)], fill=WHITE)
    return img


SPRITES = [
    ("ICON_RAPID", draw_icon_rapid(16), 16),
    ("ICON_HEAT", draw_icon_heat_resist(16), 16),
    ("ICON_LIFE", draw_icon_life(16), 16),
    ("BTN_BUY", draw_btn_buy(), None),
    ("BTN_MAX", draw_btn_max(), None),
    ("BTN_CONTINUE", draw_btn_continue(), None),
]


def to_rgb15(img):
    w, h = img.size
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            r5 = (r * 31 + 127) // 255
            g5 = (g * 31 + 127) // 255
            b5 = (b * 31 + 127) // 255
            alpha_bit = 0x8000 if a > 127 else 0
            out.append(alpha_bit | (b5 << 10) | (g5 << 5) | r5)
    return out


def write_header():
    path = os.path.join(PROJECT, "source", "shop_sprites_data.h")
    with open(path, "w") as f:
        f.write("// Generated by tools/gen_shop_sprites.py - do not edit by hand.\n")
        f.write("#ifndef BUGSWARM_SHOP_SPRITES_DATA_H\n#define BUGSWARM_SHOP_SPRITES_DATA_H\n\n")
        f.write('#include "globals.h"\n\n')
        for name, img, _label_size in SPRITES:
            data = to_rgb15(img)
            f.write(f"static const u16 SPR_{name}[{len(data)}] = {{\n")
            for i in range(0, len(data), 12):
                row = ", ".join(f"0x{v:04X}" for v in data[i:i + 12])
                f.write(f"    {row},\n")
            f.write("};\n\n")
        f.write("#endif\n")
    print("wrote", path)


def write_preview():
    scale = 6
    pad = 2
    label_h = 12
    cols = 3
    rows = 2
    cell_w = 64 * scale
    cell_h = 32 * scale
    sheet_w = cols * (cell_w + pad * 2)
    sheet_h = rows * (cell_h + pad * 2 + label_h)

    sheet = Image.new("RGBA", (sheet_w, sheet_h), (24, 24, 32, 255))
    d = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    for idx, (name, img, _s) in enumerate(SPRITES):
        col = idx % cols
        row = idx // cols
        ox = col * (cell_w + pad * 2) + pad
        oy = row * (cell_h + pad * 2 + label_h) + pad

        check = Image.new("RGBA", (cell_w, cell_h), (40, 40, 52, 255))
        cd = ImageDraw.Draw(check)
        step = scale * 2
        for yy in range(0, cell_h, step):
            for xx in range(0, cell_w, step):
                if ((xx // step) + (yy // step)) % 2 == 0:
                    cd.rectangle([xx, yy, xx + step - 1, yy + step - 1], fill=(52, 52, 66, 255))
        sheet.alpha_composite(check, (ox, oy))

        w, h = img.size
        big = img.resize((w * scale, h * scale), Image.NEAREST)
        inset_x = (cell_w - w * scale) // 2
        inset_y = (cell_h - h * scale) // 2
        sheet.alpha_composite(big, (ox + inset_x, oy + inset_y))
        d.rectangle([ox, oy, ox + cell_w - 1, oy + cell_h - 1], outline=(90, 90, 110, 255))

        label = f"{name} {w}x{h}"
        tw = d.textlength(label, font=font) if font else len(label) * 6
        d.text((ox + (cell_w - tw) / 2, oy + cell_h + 1), label, fill=(230, 230, 240, 255), font=font)

    out_path = os.path.join(OUT_DIR, "shop_sprites_preview.png")
    sheet.convert("RGB").save(out_path)
    print("wrote", out_path)


if __name__ == "__main__":
    write_header()
    write_preview()
