"""
Imports a hand-reworked tools/spritesheet_preview.png back into the game.

The sheet keeps the 4x2 grid + labels this project's gen_sprites.py lays
out, so each of the 8 cells is located the same way, then the actual
artwork is auto-cropped to its alpha bounding box (ignoring the label
strip at the bottom of each cell) and resized down to the sprite's native
in-game size with a quality (Lanczos) filter.

Output (same contract as gen_sprites.py, so sprites.c doesn't change):
  - source/spritesheet_data.h   RGB15+alpha pixel arrays the game loads
  - tools/spritesheet_ingame_preview.png   10x-scaled preview of exactly
    what ends up in VRAM, so tiny-scale readability can be checked without
    an emulator.

Run with: python tools/import_spritesheet.py
"""

import os
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(OUT_DIR)
SHEET_PATH = os.path.join(OUT_DIR, "spritesheet_preview.png")

# (name, native size, grid row, grid col) - must match gen_sprites.py's layout
SPRITES = [
    ("PLAYER",   16, 0, 0),
    ("BULLET",    8, 0, 1),
    ("CRAWLER",  16, 0, 2),
    ("SPLITTER", 16, 0, 3),
    ("MINI",      8, 1, 0),
    ("QUEEN",    32, 1, 1),
    ("OBSTACLE", 16, 1, 2),
    ("POWERUP",   8, 1, 3),
]
GRID_COLS, GRID_ROWS = 4, 2
CELL_INSET = 0.015     # trims the thin cell-outline rectangle before bbox search
ALPHA_THRESHOLD = 32
LABEL_ROW_COVERAGE = 0.9  # a row this saturated with opaque pixels is the caption bar, not art
LABEL_MARGIN = 4          # extra px trimmed above the detected caption bar


def find_label_top(img, x0, x1, y0, y1):
    """Returns the y (absolute) where the solid "NAME WxH" caption bar starts,
    by scanning the bottom half of the cell for the first fully-opaque row."""
    alpha = img.split()[-1]
    apx = alpha.load()
    width = x1 - x0
    scan_from = y0 + (y1 - y0) // 2
    for y in range(scan_from, y1):
        cnt = sum(1 for x in range(x0, x1, 2) if apx[x, y] > 100)
        if cnt / (width / 2) > LABEL_ROW_COVERAGE:
            return y
    return y1  # no caption bar found - don't trim anything


def load_cell(img, row, col):
    W, H = img.size
    cw, ch = W / GRID_COLS, H / GRID_ROWS
    x0, x1 = int(col * cw), int((col + 1) * cw)
    y0, y1 = int(row * ch), int((row + 1) * ch)
    ix0 = x0 + int(cw * CELL_INSET)
    ix1 = x1 - int(cw * CELL_INSET)
    iy0 = y0 + int(ch * CELL_INSET)
    label_top = find_label_top(img, ix0, ix1, y0, y1)
    iy1 = max(iy0 + 1, label_top - LABEL_MARGIN)
    return img.crop((ix0, iy0, ix1, iy1))


def tight_crop(cell):
    alpha = cell.split()[-1]
    mask = alpha.point(lambda a: 255 if a > ALPHA_THRESHOLD else 0)
    bbox = mask.getbbox()
    if bbox is None:
        return cell
    return cell.crop(bbox)


def to_rgb15_bytes_list(img):
    w, h = img.size
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            r5 = (r * 31 + 127) // 255
            g5 = (g * 31 + 127) // 255
            b5 = (b * 31 + 127) // 255
            alpha_bit = 0x8000 if a > 127 else 0
            out.append(alpha_bit | (b5 << 10) | (g5 << 5) | r5)
    return out


def write_header(extracted):
    path = os.path.join(PROJECT, "source", "spritesheet_data.h")
    with open(path, "w") as f:
        f.write("// Generated by tools/import_spritesheet.py - do not edit by hand.\n")
        f.write("// Source art: tools/spritesheet_preview.png\n")
        f.write("#ifndef BUGSWARM_SPRITESHEET_DATA_H\n#define BUGSWARM_SPRITESHEET_DATA_H\n\n")
        f.write('#include "globals.h"\n\n')
        for name, img, _size in extracted:
            data = to_rgb15_bytes_list(img)
            f.write(f"static const u16 SPR_{name}[{len(data)}] = {{\n")
            for i in range(0, len(data), 12):
                row = ", ".join(f"0x{v:04X}" for v in data[i:i + 12])
                f.write(f"    {row},\n")
            f.write("};\n\n")
        f.write("#endif\n")
    print("wrote", path)


def write_preview(extracted):
    scale = 10
    pad = 2
    label_h = 12
    cell = max(size for _, _, size in extracted)
    cols = 4
    rows = (len(extracted) + cols - 1) // cols
    cell_px = cell * scale
    sheet_w = cols * (cell_px + pad * 2)
    sheet_h = rows * (cell_px + pad * 2 + label_h)

    sheet = Image.new("RGBA", (sheet_w, sheet_h), (24, 24, 32, 255))
    d = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    for idx, (name, img, size) in enumerate(extracted):
        col = idx % cols
        row = idx // cols
        ox = col * (cell_px + pad * 2) + pad
        oy = row * (cell_px + pad * 2 + label_h) + pad

        check = Image.new("RGBA", (cell_px, cell_px), (40, 40, 52, 255))
        cd = ImageDraw.Draw(check)
        step = scale * 2
        for yy in range(0, cell_px, step):
            for xx in range(0, cell_px, step):
                if ((xx // step) + (yy // step)) % 2 == 0:
                    cd.rectangle([xx, yy, xx + step - 1, yy + step - 1], fill=(52, 52, 66, 255))
        sheet.alpha_composite(check, (ox, oy))

        big = img.resize((size * scale, size * scale), Image.NEAREST)
        inset = (cell_px - size * scale) // 2
        sheet.alpha_composite(big, (ox + inset, oy + inset))
        d.rectangle([ox, oy, ox + cell_px - 1, oy + cell_px - 1], outline=(90, 90, 110, 255))

        label = f"{name} {size}x{size}"
        tw = d.textlength(label, font=font) if font else len(label) * 6
        d.text((ox + (cell_px - tw) / 2, oy + cell_px + 1), label, fill=(230, 230, 240, 255), font=font)

    out_path = os.path.join(OUT_DIR, "spritesheet_ingame_preview.png")
    sheet.convert("RGB").save(out_path)
    print("wrote", out_path)


def main():
    sheet = Image.open(SHEET_PATH).convert("RGBA")
    print("loaded", SHEET_PATH, sheet.size)

    extracted = []
    for name, size, row, col in SPRITES:
        cell = load_cell(sheet, row, col)
        art = tight_crop(cell)
        resized = art.resize((size, size), Image.LANCZOS)
        extracted.append((name, resized, size))
        print(f"{name}: cell art bbox {art.size} -> {size}x{size}")

    write_header(extracted)
    write_preview(extracted)


if __name__ == "__main__":
    main()
